version: '3'
services:
  processor:
    build:
      context: .
      dockerfile: Dockerfile.processor
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '4'
    volumes:
      - ./data:/data
      - ./src:/app/src
      - /home/jj1049/.ssh/id_rsa:/app/ssh_key
    environment:
      BASE_DIR: /data
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      STORAGE_SERVER_IP: ${STORAGE_SERVER_IP}
      STORAGE_SERVER_USERNAME: ${STORAGE_SERVER_USERNAME}
      STORAGE_SERVER_DATA_PATH: ${STORAGE_SERVER_DATA_PATH}
      THUMBNAIL_TABLE: ${THUMBNAIL_TABLE}
      DATASETS_TABLE: ${DATASETS_TABLE}
      METADATA_TABLE: ${METADATA_TABLE}
      COGS_TABLE: ${COGS_TABLE}
      LABELS_TABLE: ${LABELS_TABLE}
      QUEUE_TABLE: ${QUEUE_TABLE}
      QUEUE_POSITION_TABLE: ${QUEUE_POSITION_TABLE}
      LOGS_TABLE: ${LOGS_TABLE}
      PROCESSOR_USERNAME: processor@deadtrees.earth
      PROCESSOR_PASSWORD: ${PROCESSOR_PASSWORD}
      SSH_PRIVATE_KEY_PASSPHRASE: ${SSH_PRIVATE_KEY_PASSPHRASE}
