services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8762:8762
    volumes:
      - ./data:/data
    environment:
      BASE_DIR: /data
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      PROCESSOR_USERNAME: processor@deadtrees.earth
      PROCESSOR_PASSWORD: ${SUPABASE_PASSWORD}
      UVICORN_PORT: 8762
      UVICORN_HOST: 0.0.0.0
  
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - ./src:/app/src
    links:
      - api
    command: echo "Run migration service as 'docker compose run --rm migrate bash'"
    environment:
      BASE_DIR: /data
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      PROCESSOR_USERNAME: processor@deadtrees.earth
      PROCESSOR_PASSWORD: ${SUPABASE_PASSWORD}
      OLD_ARCHIVE_PATH: /data/to_migrate
      API_URL: http://api:8762

      # migration metadata
      MIGRATION_TABLE: migrate_v1
