services:
  api-test:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - '5678:5678'
    volumes:
      - ./data:/data
      - ./src:/app/src
      - ./api/tests:/app/api/tests
      - ./api/gadm:/app/api/gadm
      - ./api/tests/test_data:/app/api/tests/test_data
      - ./import_data.py:/app/import_data.py
    environment:
      BASE_DIR: /data
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      STORAGE_SERVER_IP: ${STORAGE_SERVER_IP}
      STORAGE_SERVER_USERNAME: ${STORAGE_SERVER_USERNAME}
      STORAGE_SERVER_DATA_PATH: ${STORAGE_SERVER_DATA_PATH}
      THUMBNAIL_TABLE: ${THUMBNAIL_TABLE}
      DATASETS_TABLE: ${DATASETS_TABLE}
      METADATA_TABLE: ${METADATA_TABLE}
      COGS_TABLE: ${COGS_TABLE}
      LABELS_TABLE: ${LABELS_TABLE}
      LABEL_OBJECTS_TABLE: ${LABEL_OBJECTS_TABLE}
      QUEUE_TABLE: ${QUEUE_TABLE}
      QUEUE_POSITION_TABLE: ${QUEUE_POSITION_TABLE}
      LOGS_TABLE: ${LOGS_TABLE}
      PROCESSOR_USERNAME: processor@deadtrees.earth
      PROCESSOR_PASSWORD: ${PROCESSOR_PASSWORD}
      PYTHONPATH: /app
    entrypoint: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m pytest
