version: '3'
services:
  processor:
    build:
      context: .
      dockerfile: processor/Dockerfile
    network_mode: host
    command: python -m processor.src.processor
    deploy:
      resources:
        limits:
          cpus: '30'
          memory: '96G'
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
    volumes:
      - ./processor:/app/processor
      - ./shared:/app/shared
      - ./assets:/app/assets
      - ${SSH_PRIVATE_KEY_PATH}:/app/ssh_key
    environment:
      BASE_DIR: /data
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      STORAGE_SERVER_IP: ${STORAGE_SERVER_IP}
      STORAGE_SERVER_USERNAME: ${STORAGE_SERVER_USERNAME}
      STORAGE_SERVER_DATA_PATH: ${STORAGE_SERVER_DATA_PATH}
      PROCESSOR_USERNAME: processor@deadtrees.earth
      PROCESSOR_PASSWORD: ${PROCESSOR_PASSWORD}
      SSH_PRIVATE_KEY_PASSPHRASE: ${SSH_PRIVATE_KEY_PASSPHRASE}
      DEV_MODE: ${DEV_MODE}
      LOGFIRE_TOKEN: ${LOGFIRE_TOKEN}

