#!/usr/bin/env bash
set -Eeuo pipefail

readonly socat_bin="${DEADTREES_BORG_RSH_SOCAT_BIN:-/usr/bin/socat}"
readonly endpoint="${DEADTREES_BORG_RSH_ENDPOINT:-127.0.0.1:42729}"

exec "$socat_bin" STDIO "TCP:$endpoint"
