#!/usr/bin/env bash
set -Eeuo pipefail

readonly socat_bin="${DEADTREES_BORG_RSH_SOCAT_BIN:-/usr/bin/socat}"
readonly socket_path="${DEADTREES_BORG_RSH_SOCKET_PATH:-/tmp/borg.sock}"

exec "$socat_bin" STDIO "UNIX-CONNECT:$socket_path"
