#!/usr/bin/env python3
"""Generate a SQL seed that loads precomputed tile embeddings + minimal dataset
scaffolding into a local Dead Trees database, so the open-vocabulary search can
be tested end-to-end WITHOUT running the processor or any segmentation model.

It reads the NDJSON dump (one tile per line: dataset_id, geo bbox, pixel bbox,
nodata_fraction, embedding) and the meta JSON (per-dataset file + 4326 bbox),
and emits a single .sql file you apply with psql after `supabase db reset`:

    python scripts/seed_tile_embeddings.py \
        --seed /tmp/tile_embeddings_seed.ndjson \
        --meta /tmp/tile_embeddings_meta.json \
        --out  /tmp/seed_tile_embeddings.sql
    psql "$SUPABASE_DB_URL" -f /tmp/seed_tile_embeddings.sql

For each dataset it upserts v2_datasets / v2_orthos / v2_statuses / v2_metadata
with the flags isDatasetViewable() requires (cog/thumbnail/metadata done +
admin_level_1), then replaces the dataset's v2_tile_embeddings. The COG imagery
itself is not seeded, so the map shows the basemap + highlight rectangles (which
use each tile's 4326 footprint) rather than the drone ortho — enough to exercise
ranking, click-to-highlight, and per-ortho search.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

# Demo metadata per dataset id (admin_level_1 just needs to be non-empty for the
# dataset to pass isDatasetViewable; values here are illustrative).
DEMO = {
	204: {"admin3": "Postfire Demo (204)", "admin1": "DEU", "year": 2022},
	211: {"admin3": "Auwald Demo (211)", "admin1": "DEU", "year": 2023},
}


def sql_str(s: str) -> str:
	return "'" + s.replace("'", "''") + "'"


def main():
	ap = argparse.ArgumentParser()
	ap.add_argument("--seed", default="/tmp/tile_embeddings_seed.ndjson", type=Path)
	ap.add_argument("--meta", default="/tmp/tile_embeddings_meta.json", type=Path)
	ap.add_argument("--out", default="/tmp/seed_tile_embeddings.sql", type=Path)
	ap.add_argument("--chunk", type=int, default=300, help="rows per INSERT")
	args = ap.parse_args()

	meta = json.loads(args.meta.read_text())
	# meta keys may be strings after json round-trip
	meta = {int(k): v for k, v in meta.items()}

	# Group tile rows per dataset.
	tiles: dict[int, list] = {}
	with open(args.seed) as f:
		for line in f:
			rec = json.loads(line)
			tiles.setdefault(rec["dataset_id"], []).append(rec)

	out = []
	out.append("-- Auto-generated by scripts/seed_tile_embeddings.py — DEMO ONLY")
	out.append("begin;")
	out.append("""
do $$
declare v_user uuid;
begin
  select coalesce(
    (select user_id from public.v2_datasets order by id limit 1),
    (select id from auth.users order by created_at limit 1)
  ) into v_user;
  if v_user is null then
    raise exception 'No user found: create a user (or seed datasets) first';
  end if;
""")

	for ds_id, m in meta.items():
		d = DEMO.get(ds_id, {"admin3": f"Demo {ds_id}", "admin1": "DEU", "year": 2022})
		bbox = m["bbox_4326"]  # [min_lon, min_lat, max_lon, max_lat]
		fname = m["file"]
		out.append(f"""
  insert into public.v2_datasets (id, user_id, file_name, license, platform, authors, aquisition_year, data_access)
  values ({ds_id}, v_user, {sql_str(fname)}, 'CC BY'::"License", 'drone'::"Platform", array['Search Demo'], {d['year']}, 'public'::access)
  on conflict (id) do update set user_id = excluded.user_id, file_name = excluded.file_name;

  insert into public.v2_orthos (dataset_id, ortho_file_name, version, ortho_file_size, bbox)
  values ({ds_id}, {sql_str(fname)}, 1, 0, 'BOX({bbox[0]} {bbox[1]},{bbox[2]} {bbox[3]})'::box2d)
  on conflict (dataset_id) do update set bbox = excluded.bbox;

  -- v2_statuses PK is on id (not dataset_id), so delete + insert instead of upsert.
  delete from public.v2_statuses where dataset_id = {ds_id};
  insert into public.v2_statuses (dataset_id, current_status, is_upload_done, is_ortho_done, is_cog_done, is_thumbnail_done, is_metadata_done, is_embeddings_done, has_error)
  values ({ds_id}, 'idle'::v2_status, true, true, true, true, true, true, false);

  insert into public.v2_metadata (dataset_id, metadata, version)
  values ({ds_id}, {sql_str(json.dumps({'gadm': {'admin_level_1': d['admin1'], 'admin_level_3': d['admin3']}}))}::jsonb, 1)
  on conflict (dataset_id) do update set metadata = excluded.metadata;
""")

	out.append("end $$;\n")

	# Tile embeddings: delete + chunked inserts with explicit vector/geometry casts.
	ids = ",".join(str(i) for i in meta)
	out.append(f"delete from public.v2_tile_embeddings where dataset_id in ({ids});")

	cols = "(dataset_id, geometry, embedding, pixel_x0, pixel_y0, pixel_x1, pixel_y1, nodata_fraction)"
	for ds_id, recs in tiles.items():
		for start in range(0, len(recs), args.chunk):
			chunk = recs[start : start + args.chunk]
			values = []
			for r in chunk:
				emb = "[" + ",".join(f"{v:.6f}" for v in r["embedding"]) + "]"
				geom = (f"st_makeenvelope({r['min_lon']},{r['min_lat']},"
						f"{r['max_lon']},{r['max_lat']},4326)")
				values.append(
					f"({ds_id}, {geom}, '{emb}'::vector(1024), "
					f"{r['pixel_x0']}, {r['pixel_y0']}, {r['pixel_x1']}, {r['pixel_y1']}, "
					f"{r['nodata_fraction']})"
				)
			out.append(f"insert into public.v2_tile_embeddings {cols} values\n" + ",\n".join(values) + ";")

	out.append("commit;")
	args.out.write_text("\n".join(out) + "\n")

	n = sum(len(v) for v in tiles.values())
	print(f"Wrote {args.out} — {len(meta)} datasets, {n} tile embeddings "
		  f"({args.out.stat().st_size/1e6:.1f} MB)")


if __name__ == "__main__":
	main()
