create type "public"."prediction_quality" as enum ('great', 'sentinel_ok', 'bad');

drop policy "Enable read access for all users" on "public"."v2_datasets";

create table "public"."dataset_audit" (
    "dataset_id" bigint generated by default as identity not null,
    "audit_date" timestamp with time zone not null default now(),
    "is_georeferenced" boolean,
    "has_valid_acquisition_date" boolean,
    "acquisition_date_notes" text,
    "has_valid_phenology" boolean,
    "phenology_notes" text,
    "deadwood_quality" prediction_quality,
    "deadwood_notes" text,
    "forest_cover_quality" prediction_quality,
    "forest_cover_notes" text,
    "aoi_done" boolean,
    "has_cog_issue" boolean,
    "cog_issue_notes" text,
    "has_thumbnail_issue" boolean,
    "thumbnail_issue_notes" text,
    "audited_by" uuid,
    "notes" text
);


alter table "public"."dataset_audit" enable row level security;

alter table "public"."privileged_users" add column "can_audit" boolean;

alter table "public"."privileged_users" add column "can_view_all_private" boolean;

CREATE UNIQUE INDEX dataset_audit_pkey ON public.dataset_audit USING btree (dataset_id);

alter table "public"."dataset_audit" add constraint "dataset_audit_pkey" PRIMARY KEY using index "dataset_audit_pkey";

alter table "public"."dataset_audit" add constraint "dataset_audit_audited_by_fkey" FOREIGN KEY (audited_by) REFERENCES auth.users(id) not valid;

alter table "public"."dataset_audit" validate constraint "dataset_audit_audited_by_fkey";

alter table "public"."dataset_audit" add constraint "dataset_audit_id_fkey" FOREIGN KEY (dataset_id) REFERENCES v2_datasets(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."dataset_audit" validate constraint "dataset_audit_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.can_view_all_private_data()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT EXISTS (
    SELECT 1 
    FROM privileged_users 
    WHERE user_id = auth.uid() 
    AND can_view_all_private = true
  );
$function$
;

create or replace view "public"."v2_full_dataset_view" as  WITH ds AS (
         SELECT v2_datasets.id,
            v2_datasets.user_id,
            v2_datasets.created_at,
            v2_datasets.file_name,
            v2_datasets.license,
            v2_datasets.platform,
            v2_datasets.project_id,
            v2_datasets.authors,
            v2_datasets.aquisition_year,
            v2_datasets.aquisition_month,
            v2_datasets.aquisition_day,
            v2_datasets.additional_information,
            v2_datasets.data_access,
            v2_datasets.citation_doi
           FROM v2_datasets
          WHERE ((v2_datasets.data_access <> 'private'::access) OR (auth.uid() = v2_datasets.user_id) OR can_view_all_private_data())
        ), ortho AS (
         SELECT v2_orthos.dataset_id,
            v2_orthos.ortho_file_name,
            v2_orthos.ortho_file_size,
            v2_orthos.bbox,
            v2_orthos.sha256,
            v2_orthos.ortho_upload_runtime
           FROM v2_orthos
        ), status AS (
         SELECT v2_statuses.dataset_id,
            v2_statuses.current_status,
            v2_statuses.is_upload_done,
            v2_statuses.is_ortho_done,
            v2_statuses.is_cog_done,
            v2_statuses.is_thumbnail_done,
            v2_statuses.is_deadwood_done,
            v2_statuses.is_forest_cover_done,
            v2_statuses.is_metadata_done,
            v2_statuses.is_audited,
            v2_statuses.has_error,
            v2_statuses.error_message
           FROM v2_statuses
        ), extra AS (
         SELECT ds_1.id AS dataset_id,
            cog.cog_file_name,
            cog.cog_path,
            cog.cog_file_size,
            thumb.thumbnail_file_name,
            thumb.thumbnail_path,
            (meta.metadata ->> 'gadm'::text) AS admin_metadata,
            (meta.metadata ->> 'biome'::text) AS biome_metadata
           FROM (((v2_datasets ds_1
             LEFT JOIN v2_cogs cog ON ((cog.dataset_id = ds_1.id)))
             LEFT JOIN v2_thumbnails thumb ON ((thumb.dataset_id = ds_1.id)))
             LEFT JOIN v2_metadata meta ON ((meta.dataset_id = ds_1.id)))
          WHERE ((ds_1.data_access <> 'private'::access) OR (auth.uid() = ds_1.user_id) OR can_view_all_private_data())
        ), label_info AS (
         SELECT dataset.id AS dataset_id,
            (EXISTS ( SELECT 1
                   FROM v2_labels
                  WHERE ((v2_labels.dataset_id = dataset.id) AND (v2_labels.label_source = 'visual_interpretation'::"LabelSource") AND (v2_labels.label_data = 'deadwood'::"LabelData")))) AS has_labels,
            (EXISTS ( SELECT 1
                   FROM v2_labels
                  WHERE ((v2_labels.dataset_id = dataset.id) AND (v2_labels.label_source = 'model_prediction'::"LabelSource") AND (v2_labels.label_data = 'deadwood'::"LabelData")))) AS has_deadwood_prediction
           FROM v2_datasets dataset
          WHERE ((dataset.data_access <> 'private'::access) OR (auth.uid() = dataset.user_id) OR can_view_all_private_data())
        ), freidata_doi AS (
         SELECT jt.dataset_id,
            dp.doi AS freidata_doi
           FROM (jt_data_publication_datasets jt
             JOIN data_publication dp ON ((dp.id = jt.publication_id)))
          WHERE (dp.doi IS NOT NULL)
        )
 SELECT ds.id,
    ds.user_id,
    ds.created_at,
    ds.file_name,
    ds.license,
    ds.platform,
    ds.project_id,
    ds.authors,
    ds.aquisition_year,
    ds.aquisition_month,
    ds.aquisition_day,
    ds.additional_information,
    ds.data_access,
    ds.citation_doi,
    ortho.ortho_file_name,
    ortho.ortho_file_size,
    ortho.bbox,
    ortho.sha256,
    status.current_status,
    status.is_upload_done,
    status.is_ortho_done,
    status.is_cog_done,
    status.is_thumbnail_done,
    status.is_deadwood_done,
    status.is_forest_cover_done,
    status.is_metadata_done,
    status.is_audited,
    status.has_error,
    status.error_message,
    extra.cog_file_name,
    extra.cog_path,
    extra.cog_file_size,
    extra.thumbnail_file_name,
    extra.thumbnail_path,
    ((extra.admin_metadata)::jsonb ->> 'admin_level_1'::text) AS admin_level_1,
    ((extra.admin_metadata)::jsonb ->> 'admin_level_2'::text) AS admin_level_2,
    ((extra.admin_metadata)::jsonb ->> 'admin_level_3'::text) AS admin_level_3,
    ((extra.biome_metadata)::jsonb ->> 'biome_name'::text) AS biome_name,
    label_info.has_labels,
    label_info.has_deadwood_prediction,
    freidata_doi.freidata_doi
   FROM (((((ds
     LEFT JOIN ortho ON ((ortho.dataset_id = ds.id)))
     LEFT JOIN status ON ((status.dataset_id = ds.id)))
     LEFT JOIN extra ON ((extra.dataset_id = ds.id)))
     LEFT JOIN label_info ON ((label_info.dataset_id = ds.id)))
     LEFT JOIN freidata_doi ON ((freidata_doi.dataset_id = ds.id)));


grant delete on table "public"."dataset_audit" to "anon";

grant insert on table "public"."dataset_audit" to "anon";

grant references on table "public"."dataset_audit" to "anon";

grant select on table "public"."dataset_audit" to "anon";

grant trigger on table "public"."dataset_audit" to "anon";

grant truncate on table "public"."dataset_audit" to "anon";

grant update on table "public"."dataset_audit" to "anon";

grant delete on table "public"."dataset_audit" to "authenticated";

grant insert on table "public"."dataset_audit" to "authenticated";

grant references on table "public"."dataset_audit" to "authenticated";

grant select on table "public"."dataset_audit" to "authenticated";

grant trigger on table "public"."dataset_audit" to "authenticated";

grant truncate on table "public"."dataset_audit" to "authenticated";

grant update on table "public"."dataset_audit" to "authenticated";

grant delete on table "public"."dataset_audit" to "service_role";

grant insert on table "public"."dataset_audit" to "service_role";

grant references on table "public"."dataset_audit" to "service_role";

grant select on table "public"."dataset_audit" to "service_role";

grant trigger on table "public"."dataset_audit" to "service_role";

grant truncate on table "public"."dataset_audit" to "service_role";

grant update on table "public"."dataset_audit" to "service_role";

create policy "Allow all for processor"
on "public"."dataset_audit"
as permissive
for all
to authenticated
using (true);


create policy "Enable read access for all users"
on "public"."v2_datasets"
as permissive
for select
to public
using (((data_access <> 'private'::access) OR (auth.uid() = user_id) OR can_view_all_private_data()));



