-- Create AOIs table
CREATE TABLE "public"."v2_aois" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dataset_id" bigint NOT NULL REFERENCES "public"."v2_datasets"(id) ON DELETE CASCADE,
    "user_id" uuid NOT NULL REFERENCES "auth"."users"(id),
    "geometry" jsonb NOT NULL,
    "is_whole_image" boolean NOT NULL DEFAULT false,
    "image_quality" smallint,
    "notes" text,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);

-- Create Labels table with label_data column included
CREATE TABLE "public"."v2_labels" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dataset_id" bigint NOT NULL REFERENCES "public"."v2_datasets"(id) ON DELETE CASCADE,
    "aoi_id" bigint REFERENCES "public"."v2_aois"(id) ON DELETE SET NULL,
    "user_id" uuid NOT NULL REFERENCES "auth"."users"(id),
    "label_source" "public"."LabelSource" NOT NULL,
    "label_type" "public"."LabelType" NOT NULL,
    "label_data" "public"."LabelData" NOT NULL,
    "label_quality" smallint,
    "model_config" jsonb,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "updated_at" timestamp with time zone NOT NULL DEFAULT now()
);

-- Create Label Geometries table
CREATE TABLE "public"."v2_label_geometries" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "label_id" bigint NOT NULL REFERENCES "public"."v2_labels"(id) ON DELETE CASCADE,
    "geometry" geometry(MULTIPOLYGON, 4326) NOT NULL,
    "properties" jsonb,
    "created_at" timestamp with time zone NOT NULL DEFAULT now()
);

-- Add indexes
CREATE INDEX idx_aois_dataset_id ON "public"."v2_aois"(dataset_id);
CREATE INDEX idx_aois_user_id ON "public"."v2_aois"(user_id);
CREATE INDEX idx_labels_dataset_id ON "public"."v2_labels"(dataset_id);
CREATE INDEX idx_labels_aoi_id ON "public"."v2_labels"(aoi_id);
CREATE INDEX idx_labels_user_id ON "public"."v2_labels"(user_id);
CREATE INDEX idx_label_geometries_label_id ON "public"."v2_label_geometries"(label_id);

-- Add spatial indexes
CREATE INDEX idx_aois_geometry ON "public"."v2_aois" USING GIN(geometry);
CREATE INDEX idx_label_geometries_geometry ON "public"."v2_label_geometries" USING GIST(geometry);

-- Ensure only one whole-image AOI per dataset
CREATE UNIQUE INDEX idx_whole_image_aoi 
ON "public"."v2_aois"(dataset_id) 
WHERE is_whole_image = true;

-- Add validation checks
ALTER TABLE "public"."v2_aois" 
ADD CONSTRAINT check_image_quality 
CHECK (image_quality BETWEEN 1 AND 3);

ALTER TABLE "public"."v2_labels" 
ADD CONSTRAINT check_label_quality 
CHECK (label_quality BETWEEN 1 AND 3); 