create table "public"."map_flags" (
    "id" bigint generated by default as identity not null,
    "created_by" uuid not null,
    "bbox" jsonb not null,
    "description" text not null,
    "category" text default 'other'::text,
    "year" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "public"."map_flags" enable row level security;

CREATE INDEX idx_map_flags_created_by ON public.map_flags USING btree (created_by);

CREATE UNIQUE INDEX map_flags_pkey ON public.map_flags USING btree (id);

alter table "public"."map_flags" add constraint "map_flags_pkey" PRIMARY KEY using index "map_flags_pkey";

alter table "public"."map_flags" add constraint "map_flags_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) not valid;

alter table "public"."map_flags" validate constraint "map_flags_created_by_fkey";

grant delete on table "public"."map_flags" to "anon";

grant insert on table "public"."map_flags" to "anon";

grant references on table "public"."map_flags" to "anon";

grant select on table "public"."map_flags" to "anon";

grant trigger on table "public"."map_flags" to "anon";

grant truncate on table "public"."map_flags" to "anon";

grant update on table "public"."map_flags" to "anon";

grant delete on table "public"."map_flags" to "authenticated";

grant insert on table "public"."map_flags" to "authenticated";

grant references on table "public"."map_flags" to "authenticated";

grant select on table "public"."map_flags" to "authenticated";

grant trigger on table "public"."map_flags" to "authenticated";

grant truncate on table "public"."map_flags" to "authenticated";

grant update on table "public"."map_flags" to "authenticated";

grant delete on table "public"."map_flags" to "service_role";

grant insert on table "public"."map_flags" to "service_role";

grant references on table "public"."map_flags" to "service_role";

grant select on table "public"."map_flags" to "service_role";

grant trigger on table "public"."map_flags" to "service_role";

grant truncate on table "public"."map_flags" to "service_role";

grant update on table "public"."map_flags" to "service_role";

create policy "Auditors can view all flags"
on "public"."map_flags"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM privileged_users
  WHERE ((privileged_users.user_id = auth.uid()) AND (privileged_users.can_audit = true)))));


create policy "Authenticated users can create flags"
on "public"."map_flags"
as permissive
for insert
to public
with check ((auth.uid() = created_by));


create policy "Users can delete own flags"
on "public"."map_flags"
as permissive
for delete
to public
using ((auth.uid() = created_by));


create policy "Users can view own flags"
on "public"."map_flags"
as permissive
for select
to public
using ((auth.uid() = created_by));



