-- Open-vocabulary tile search storage + ranking.
--
-- The embeddings_v1 processor stage reprojects each orthophoto to 10cm, tiles it
-- into 512px windows, drops tiles with >50% nodata, and embeds the rest with
-- OpenCLIP ViT-H/14 (1024-dim, L2-normalized). Each tile is stored here with its
-- WGS84 footprint so the frontend can rank datasets/tiles against a text query
-- and highlight matching tiles on the map.

create extension if not exists vector;

create table if not exists public.v2_tile_embeddings (
  id bigint generated by default as identity primary key,
  dataset_id bigint not null references public.v2_datasets (id) on delete cascade,
  -- Tile footprint in EPSG:4326 (used for map highlighting / spatial filtering).
  geometry geometry(Polygon, 4326) not null,
  -- L2-normalized OpenCLIP ViT-H/14 image embedding.
  embedding vector(1024) not null,
  -- Pixel window in the reprojected 10cm raster (debug / reproducibility).
  pixel_x0 integer not null,
  pixel_y0 integer not null,
  pixel_x1 integer not null,
  pixel_y1 integer not null,
  nodata_fraction real not null default 0,
  -- Rows are inserted inactive and atomically activated after the full dataset
  -- batch is present, so failed first runs never become searchable.
  is_active boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists v2_tile_embeddings_dataset_id_idx
  on public.v2_tile_embeddings (dataset_id);

create index if not exists v2_tile_embeddings_active_dataset_id_idx
  on public.v2_tile_embeddings (dataset_id)
  where is_active;

create index if not exists v2_tile_embeddings_geometry_idx
  on public.v2_tile_embeddings using gist (geometry);

-- HNSW cosine index accelerates nearest-neighbour ranking against a query vector.
create index if not exists v2_tile_embeddings_embedding_idx
  on public.v2_tile_embeddings using hnsw (embedding vector_cosine_ops);

-- Grants mirror v2_aois: API roles read, authenticated (incl. processor) write,
-- service_role full access.
grant select on table public.v2_tile_embeddings to anon, authenticated;
grant insert, update, delete on table public.v2_tile_embeddings to authenticated;
grant all on table public.v2_tile_embeddings to service_role;

alter table public.v2_tile_embeddings enable row level security;

-- Public read access follows dataset visibility, mirroring the v2_aois policy.
drop policy if exists "Allow public read access to tile embeddings" on public.v2_tile_embeddings;
create policy "Allow public read access to tile embeddings"
  on public.v2_tile_embeddings
  for select
  to public
  using (
    is_active
    and exists (
      select 1
      from public.v2_statuses s
      where s.dataset_id = v2_tile_embeddings.dataset_id
        and s.is_embeddings_done = true
    )
    and
    exists (
      select 1
      from public.v2_datasets d
      where d.id = v2_tile_embeddings.dataset_id
        and (
          d.data_access <> 'private'::access
          or auth.uid() = d.user_id
          or can_view_all_private_data()
          or ((auth.jwt() ->> 'email'::text) = 'processor@deadtrees.earth'::text)
        )
        and (
          d.archived = false
          or auth.uid() = d.user_id
        )
        and (
          auth.uid() = d.user_id
          or can_view_all_private_data()
          or ((auth.jwt() ->> 'email'::text) = 'processor@deadtrees.earth'::text)
          or not internal.is_dataset_excluded_from_public_surface(d.id)
        )
    )
  );

-- Only the processor automation writes embeddings (one row set per dataset,
-- replaced on rerun). Allow authenticated processor inserts/deletes.
drop policy if exists "Allow processor to write tile embeddings" on public.v2_tile_embeddings;
create policy "Allow processor to write tile embeddings"
  on public.v2_tile_embeddings
  for insert
  to authenticated
  with check (
    (auth.jwt() ->> 'email'::text) = 'processor@deadtrees.earth'::text
  );

drop policy if exists "Allow processor to delete tile embeddings" on public.v2_tile_embeddings;
create policy "Allow processor to delete tile embeddings"
  on public.v2_tile_embeddings
  for delete
  to authenticated
  using (
    (auth.jwt() ->> 'email'::text) = 'processor@deadtrees.earth'::text
  );

-- Shared visibility predicate, evaluated against the calling user inside the
-- SECURITY DEFINER ranking functions below.
create or replace function public.is_dataset_search_visible(p_dataset_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.v2_datasets d
    where d.id = p_dataset_id
      and (
        d.data_access <> 'private'::access
        or auth.uid() = d.user_id
        or can_view_all_private_data()
        or ((auth.jwt() ->> 'email'::text) = 'processor@deadtrees.earth'::text)
      )
      and (
        d.archived = false
        or auth.uid() = d.user_id
      )
      and (
        auth.uid() = d.user_id
        or can_view_all_private_data()
        or ((auth.jwt() ->> 'email'::text) = 'processor@deadtrees.earth'::text)
        or not internal.is_dataset_excluded_from_public_surface(d.id)
      )
  );
$$;

-- Search should only publish datasets whose embedding generation has completed.
-- Combined with per-row is_active, this prevents failed first runs and partially
-- inserted reruns from leaking into search results.
create or replace function public.is_dataset_search_ready(p_dataset_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.v2_statuses s
    where s.dataset_id = p_dataset_id
      and s.is_embeddings_done = true
  );
$$;

-- Rank datasets by their single best-matching tile against a query embedding.
-- query_embedding is passed as a pgvector text literal ('[v1,v2,...]') so the
-- API can send it through PostgREST without vector-typed RPC params.
create or replace function public.search_datasets_by_embedding(
  query_embedding text,
  match_count integer default 50,
  min_similarity double precision default 0.0
)
returns table (
  dataset_id bigint,
  similarity double precision,
  tile_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with q as (select query_embedding::vector(1024) as v)
  select
    e.dataset_id,
    max(1 - (e.embedding <=> q.v))::double precision as similarity,
    count(*)::bigint as tile_count
  from public.v2_tile_embeddings e
  cross join q
  where e.is_active
    and public.is_dataset_search_ready(e.dataset_id)
    and public.is_dataset_search_visible(e.dataset_id)
  group by e.dataset_id
  having max(1 - (e.embedding <=> q.v)) >= min_similarity
  order by similarity desc
  limit greatest(match_count, 1);
$$;

-- Rank the individual tiles of one dataset against a query embedding and return
-- their footprints as GeoJSON for map highlighting.
create or replace function public.search_tiles_by_embedding(
  query_embedding text,
  p_dataset_id bigint,
  match_count integer default 200
)
returns table (
  id bigint,
  similarity double precision,
  nodata_fraction real,
  geometry json
)
language sql
stable
security definer
set search_path = public
as $$
  with q as (select query_embedding::vector(1024) as v)
  select
    e.id,
    (1 - (e.embedding <=> q.v))::double precision as similarity,
    e.nodata_fraction,
    st_asgeojson(e.geometry)::json as geometry
  from public.v2_tile_embeddings e
  cross join q
  where e.dataset_id = p_dataset_id
    and e.is_active
    and public.is_dataset_search_ready(e.dataset_id)
    and public.is_dataset_search_visible(e.dataset_id)
  order by similarity desc
  limit greatest(match_count, 1);
$$;

-- Insert a batch of tile embeddings for a dataset. The processor passes rows as
-- JSON (embedding as a pgvector text literal, footprint as a lon/lat envelope)
-- and this function casts them to vector/geometry server-side, which is far more
-- robust than inserting vector/geometry columns directly through PostgREST.
create or replace function public.insert_tile_embeddings(
  p_dataset_id bigint,
  p_rows jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted integer;
begin
  if (auth.jwt() ->> 'email'::text) is distinct from 'processor@deadtrees.earth'::text then
    raise exception 'not authorized to write tile embeddings';
  end if;

  insert into public.v2_tile_embeddings
    (dataset_id, geometry, embedding, pixel_x0, pixel_y0, pixel_x1, pixel_y1, nodata_fraction)
  select
    p_dataset_id,
    st_makeenvelope(r.min_lon, r.min_lat, r.max_lon, r.max_lat, 4326),
    r.embedding::vector(1024),
    r.pixel_x0, r.pixel_y0, r.pixel_x1, r.pixel_y1, r.nodata_fraction
  from jsonb_to_recordset(p_rows) as r(
    min_lon double precision,
    min_lat double precision,
    max_lon double precision,
    max_lat double precision,
    embedding text,
    pixel_x0 integer,
    pixel_y0 integer,
    pixel_x1 integer,
    pixel_y1 integer,
    nodata_fraction real
  );

  get diagnostics inserted = row_count;
  return inserted;
end;
$$;

-- Publish the newly inserted inactive rows for a dataset in one database
-- transaction, then remove the previous active generation. Until this RPC
-- commits, readers continue seeing the old complete generation (if any).
create or replace function public.activate_tile_embeddings(
  p_dataset_id bigint,
  p_old_max_id bigint default null,
  p_expected_count integer default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  activated integer;
begin
  if (auth.jwt() ->> 'email'::text) is distinct from 'processor@deadtrees.earth'::text then
    raise exception 'not authorized to activate tile embeddings';
  end if;

  update public.v2_tile_embeddings
  set is_active = true
  where dataset_id = p_dataset_id
    and is_active = false
    and (p_old_max_id is null or id > p_old_max_id);

  get diagnostics activated = row_count;

  if p_expected_count is not null and activated <> p_expected_count then
    raise exception 'activated % tile embeddings, expected %', activated, p_expected_count;
  end if;

  if p_old_max_id is not null then
    delete from public.v2_tile_embeddings
    where dataset_id = p_dataset_id
      and id <= p_old_max_id;
  end if;

  return activated;
end;
$$;

grant execute on function public.is_dataset_search_visible(bigint) to anon, authenticated, service_role;
grant execute on function public.is_dataset_search_ready(bigint) to anon, authenticated, service_role;
grant execute on function public.insert_tile_embeddings(bigint, jsonb) to authenticated, service_role;
grant execute on function public.activate_tile_embeddings(bigint, bigint, integer) to authenticated, service_role;
grant execute on function public.search_datasets_by_embedding(text, integer, double precision) to anon, authenticated, service_role;
grant execute on function public.search_tiles_by_embedding(text, bigint, integer) to anon, authenticated, service_role;
