-- Log open-vocabulary search queries for analytics.
--
-- Both the global dataset search (/dataset archive) and the per-orthophoto tile
-- search embed a free-text query and rank against it. This table records what
-- was searched: the text, the user, and the dataset (only for the dataset-scoped
-- tile search; NULL for the global search). Logging happens client-side because
-- that is where both the user identity and the dataset context are known — the
-- /search/embed API endpoint only sees the raw text. Inserts are limited to
-- authenticated users (the search UI is auth-gated); anon has no write path.

create table "public"."v2_search_queries" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    -- Cap the length so no single row can be bloated into a large blob. Real
    -- search queries are short; 500 chars is far more than any UI can produce.
    "query" text not null check (char_length(query) <= 500),
    -- Filled from the caller's JWT by default. Only authenticated users may
    -- insert (see grants below), so in practice this is always populated.
    "user_id" uuid default auth.uid(),
    -- Set only for dataset-scoped tile searches; NULL for the global search.
    "dataset_id" bigint
);

alter table "public"."v2_search_queries" enable row level security;

CREATE UNIQUE INDEX v2_search_queries_pkey ON public.v2_search_queries USING btree (id);
alter table "public"."v2_search_queries" add constraint "v2_search_queries_pkey" PRIMARY KEY using index "v2_search_queries_pkey";

-- Keep the log row if the user or dataset is later removed (analytics history),
-- just null the reference.
alter table "public"."v2_search_queries"
  add constraint "v2_search_queries_user_id_fkey"
  foreign key (user_id) references auth.users(id) on delete set null not valid;
alter table "public"."v2_search_queries" validate constraint "v2_search_queries_user_id_fkey";

alter table "public"."v2_search_queries"
  add constraint "v2_search_queries_dataset_id_fkey"
  foreign key (dataset_id) references public.v2_datasets(id) on delete set null not valid;
alter table "public"."v2_search_queries" validate constraint "v2_search_queries_dataset_id_fkey";

-- Analytics access patterns: recent-first, and per-dataset.
CREATE INDEX v2_search_queries_created_at_idx ON public.v2_search_queries USING btree (created_at desc);
CREATE INDEX v2_search_queries_dataset_id_idx ON public.v2_search_queries USING btree (dataset_id);

-- Deliberately NO grant to anon: with the public anon key that would let an
-- unauthenticated client write arbitrary rows directly, bypassing the
-- rate-limited /search/embed endpoint and inviting log spam. The search UI is
-- authenticated-only anyway, so logging is scoped to authenticated users. If
-- anonymous search is ever exposed, log it server-side through the rate-limited
-- API instead of re-granting a direct anon insert.
-- authenticated gets SELECT too, but the RLS policy below still restricts which
-- rows they see (auditors only) — the grant is necessary but not sufficient.
grant select, insert on table "public"."v2_search_queries" to "authenticated";
grant select, insert on table "public"."v2_search_queries" to "service_role";

-- Insert: an authenticated user may log a query, but only attributed to
-- themselves — user_id must equal their own auth.uid(). The column default
-- supplies that value, so clients just send { query, dataset_id }.
create policy "Users can log their own search query"
on "public"."v2_search_queries"
as permissive
for insert
to authenticated
with check (user_id = auth.uid());

-- Read: analytics only — restricted to auditors.
create policy "Auditors can read the search query log"
on "public"."v2_search_queries"
as permissive
for select
to authenticated
using (exists (
  select 1 from public.privileged_users
  where privileged_users.user_id = auth.uid()
    and privileged_users.can_audit = true
));
