-- Acquisition-date decisions: the outcome of the date check, versioned.
--
-- The model's estimate (v2_acquisition_date_estimates) and its audit
-- suggestions only propose. A *decision* is what was concluded: whether the
-- reported date is valid, and whether the suggested date was accepted. It is
-- made by an auditor (saving the audit form) or, when enabled, automatically
-- by the processor. Exactly one decision per dataset is active; older ones are
-- never overwritten but deactivated with a date and a reason:
--   new_decision          a newer decision replaced it (re-audit)
--   estimate_contradicts  a new estimate (rerun, new model version) disagrees
--   date_edited           the dataset's date was edited by hand
--   cutoff                an operator deactivated all decisions before a date
-- A deactivated decision sends the date step back to review: the audit's date
-- fields are cleared, so the form is prefilled from the current suggestions.
--
-- Accepting the suggested date writes it to v2_datasets (full day) and marks
-- the date as aquisition_date_source = 'model_suggestion' with a pointer to the
-- decision, whose evidence snapshot (distribution, ranges, offset, surprise)
-- explains the change; the reported date is kept on the decision.

alter table public.dataset_audit
  add column if not exists accept_suggested_acquisition_date boolean;

create table if not exists public.acquisition_date_decisions (
  id bigint generated by default as identity primary key,
  dataset_id bigint not null references public.v2_datasets (id) on delete cascade,
  source text not null check (source in ('auditor', 'automatic', 'legacy_audit')),
  decided_by uuid references auth.users (id) on delete set null,
  decided_at timestamptz not null default now(),
  -- is the reported date plausible?
  date_valid boolean not null,
  -- the suggested date: accepted, rejected, or null when there was none / undecided
  suggestion_decision text check (suggestion_decision in ('accepted', 'rejected')),
  suggested_date date,
  -- the dataset's date before (as reported) and after this decision
  reported_year smallint,
  reported_month smallint,
  reported_day smallint,
  resulting_year smallint,
  resulting_month smallint,
  resulting_day smallint,
  estimate_model_version text,
  estimate_model_type text,
  -- snapshot of the estimate the decision was based on (probabilities, ranges,
  -- offset, surprise, modes), so the evidence survives later reruns
  evidence jsonb not null default '{}'::jsonb,
  superseded_at timestamptz,
  superseded_reason text check (superseded_reason in ('new_decision', 'estimate_contradicts', 'date_edited', 'cutoff')),
  check ((superseded_at is null) = (superseded_reason is null)),
  check (suggestion_decision is distinct from 'accepted' or suggested_date is not null)
);

create unique index if not exists acquisition_date_decisions_one_active_idx
  on public.acquisition_date_decisions (dataset_id) where superseded_at is null;
create index if not exists acquisition_date_decisions_dataset_idx
  on public.acquisition_date_decisions (dataset_id, decided_at desc);

alter table public.v2_datasets
  add column if not exists aquisition_date_source text not null default 'reported'
    check (aquisition_date_source in ('reported', 'model_suggestion')),
  add column if not exists aquisition_date_decision_id bigint
    references public.acquisition_date_decisions (id) on delete set null;

-- Read like the dataset (the dataset page explains a model-suggested date);
-- written only through the functions below.
grant select on table public.acquisition_date_decisions to anon, authenticated;
grant all on table public.acquisition_date_decisions to service_role;
alter table public.acquisition_date_decisions enable row level security;

drop policy if exists "Read acquisition date decisions like the dataset" on public.acquisition_date_decisions;
create policy "Read acquisition date decisions like the dataset"
  on public.acquisition_date_decisions
  for select
  to public
  using (
    exists (
      select 1
      from public.v2_datasets d
      where d.id = acquisition_date_decisions.dataset_id
        and (
          d.data_access <> 'private'::access
          or auth.uid() = d.user_id
          or can_view_all_private_data()
          or ((auth.jwt() ->> 'email'::text) = 'processor@deadtrees.earth'::text)
        )
        and (d.archived = false or auth.uid() = d.user_id)
    )
  );

grant select on public.acquisition_date_decisions to analyst;
drop policy if exists analyst_select on public.acquisition_date_decisions;
create policy analyst_select on public.acquisition_date_decisions for select to analyst using (true);

-- Existing audits become the first (legacy) decisions, dated by their audit.
insert into public.acquisition_date_decisions (
  dataset_id, source, decided_by, decided_at, date_valid,
  reported_year, reported_month, reported_day, resulting_year, resulting_month, resulting_day
)
select a.dataset_id, 'legacy_audit', a.audited_by, coalesce(a.audit_date, now()), a.has_valid_acquisition_date,
  d.aquisition_year, d.aquisition_month, d.aquisition_day, d.aquisition_year, d.aquisition_month, d.aquisition_day
from public.dataset_audit a
join public.v2_datasets d on d.id = a.dataset_id
where a.has_valid_acquisition_date is not null
  and not exists (select 1 from public.acquisition_date_decisions x where x.dataset_id = a.dataset_id);

-- Deactivate a dataset's active decision and send its date step back to review.
create or replace function public.supersede_acquisition_date_decision(p_dataset_id bigint, p_reason text)
returns bigint language plpgsql security definer set search_path = '' as $$
declare
    v_id bigint;
begin
    update public.acquisition_date_decisions
    set superseded_at = now(), superseded_reason = p_reason
    where dataset_id = p_dataset_id and superseded_at is null
    returning id into v_id;
    if v_id is not null and p_reason <> 'new_decision' then
        update public.dataset_audit
        set has_valid_acquisition_date = null, accept_suggested_acquisition_date = null
        where dataset_id = p_dataset_id;
    end if;
    return v_id;
end;
$$;
revoke all on function public.supersede_acquisition_date_decision(bigint, text) from public, anon, authenticated;

-- The one place a date decision is recorded and applied.
create or replace function public.record_acquisition_date_decision(
    p_dataset_id bigint, p_date_valid boolean, p_accept boolean, p_source text, p_decided_by uuid
)
returns bigint language plpgsql security definer set search_path = '' as $$
declare
    v_ds record;
    v_est record;
    v_active record;
    v_suggestion text;
    v_rep smallint[];
    v_res smallint[];
    v_id bigint;
begin
    select d.aquisition_year, d.aquisition_month, d.aquisition_day, d.aquisition_date_source
    into v_ds from public.v2_datasets d where d.id = p_dataset_id for update;
    if not found then
        raise exception 'Dataset % not found', p_dataset_id using errcode = 'P0002';
    end if;
    select * into v_est from public.v2_acquisition_date_estimates e where e.dataset_id = p_dataset_id;
    select * into v_active from public.acquisition_date_decisions a
    where a.dataset_id = p_dataset_id and a.superseded_at is null;

    -- a machine never overrides a person
    if p_source = 'automatic' and v_active.id is not null and v_active.source <> 'automatic' then
        return v_active.id;
    end if;

    v_suggestion := case
        when p_accept is true then 'accepted'
        when p_accept is false and v_est.suggested_date is not null then 'rejected'
    end;
    -- re-saving the same outcome is not a new decision
    if v_active.id is not null and v_active.source = p_source
        and v_active.date_valid = p_date_valid
        and v_active.suggestion_decision is not distinct from v_suggestion then
        return v_active.id;
    end if;

    -- the reported date: the current one, or the one an accepted suggestion replaced
    if v_ds.aquisition_date_source = 'model_suggestion' and v_active.id is not null then
        v_rep := array[v_active.reported_year, v_active.reported_month, v_active.reported_day];
    else
        v_rep := array[v_ds.aquisition_year, v_ds.aquisition_month, v_ds.aquisition_day];
    end if;

    if p_accept is true then
        if v_est.suggested_date is null then
            raise exception 'Dataset % has no suggested acquisition date', p_dataset_id using errcode = '23514';
        end if;
        if array[v_est.recorded_year, v_est.recorded_month, v_est.recorded_day] is distinct from v_rep then
            raise exception 'The acquisition date of dataset % changed since the suggestion was made; rerun doy_estimation_v1', p_dataset_id
                using errcode = '40001';
        end if;
        v_res := array[extract(year from v_est.suggested_date), extract(month from v_est.suggested_date), extract(day from v_est.suggested_date)]::smallint[];
    else
        v_res := v_rep;
    end if;

    perform public.supersede_acquisition_date_decision(p_dataset_id, 'new_decision');
    insert into public.acquisition_date_decisions (
        dataset_id, source, decided_by, date_valid, suggestion_decision, suggested_date,
        reported_year, reported_month, reported_day, resulting_year, resulting_month, resulting_day,
        estimate_model_version, estimate_model_type, evidence
    ) values (
        p_dataset_id, p_source, p_decided_by, p_date_valid, v_suggestion,
        case when v_suggestion is not null then v_est.suggested_date end,
        v_rep[1], v_rep[2], v_rep[3], v_res[1], v_res[2], v_res[3],
        v_est.model_version, v_est.model_type,
        case when v_est.dataset_id is null then '{}'::jsonb else jsonb_build_object(
            'flight_year', v_est.flight_year,
            'probabilities', to_jsonb(v_est.probabilities),
            'predicted_date', v_est.predicted_date,
            'hdi', v_est.hdi,
            'hdi80_days', v_est.hdi80_days,
            'n_modes', v_est.n_modes,
            'recorded_surprise', v_est.recorded_surprise,
            'recorded_offset_days', v_est.recorded_offset_days,
            'is_mismatch', v_est.is_mismatch,
            'suggestion_reason', v_est.suggestion_reason,
            'recommend_accept', v_est.recommend_accept,
            'estimated_at', v_est.updated_at
        ) end
    ) returning id into v_id;

    -- apply the resulting date and where it came from; a plain valid/invalid
    -- verdict on a reported date leaves the dataset row untouched
    perform set_config('deadtrees.recording_date_decision', 'on', true);
    update public.v2_datasets
    set aquisition_year = v_res[1], aquisition_month = v_res[2], aquisition_day = v_res[3],
        aquisition_date_source = case when v_suggestion = 'accepted' then 'model_suggestion' else 'reported' end,
        aquisition_date_decision_id = case when v_suggestion = 'accepted' then v_id end
    where id = p_dataset_id
        and (array[aquisition_year, aquisition_month, aquisition_day] is distinct from v_res
            or aquisition_date_source is distinct from case when v_suggestion = 'accepted' then 'model_suggestion' else 'reported' end
            or aquisition_date_decision_id is distinct from case when v_suggestion = 'accepted' then v_id end);
    perform set_config('deadtrees.recording_date_decision', 'off', true);
    return v_id;
end;
$$;
revoke all on function public.record_acquisition_date_decision(bigint, boolean, boolean, text, uuid) from public, anon, authenticated;

-- Saving the audit form records the auditor's date decision (behind the audit
-- lease guard, which sorts first). Cleared fields (a deactivated decision) are
-- not a decision.
create or replace function public.record_audit_date_decision()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
    if new.has_valid_acquisition_date is null then
        return new;
    end if;
    if tg_op = 'UPDATE'
        and new.has_valid_acquisition_date is not distinct from old.has_valid_acquisition_date
        and new.accept_suggested_acquisition_date is not distinct from old.accept_suggested_acquisition_date then
        return new;
    end if;
    perform public.record_acquisition_date_decision(
        new.dataset_id, new.has_valid_acquisition_date, new.accept_suggested_acquisition_date,
        'auditor', coalesce(auth.uid(), new.audited_by));
    return new;
end;
$$;
revoke all on function public.record_audit_date_decision() from public, anon, authenticated;
drop trigger if exists record_audit_date_decision on public.dataset_audit;
create trigger record_audit_date_decision
after insert or update of has_valid_acquisition_date, accept_suggested_acquisition_date on public.dataset_audit
for each row execute function public.record_audit_date_decision();

-- A hand edit of the date (upload form, owner edit) makes it a reported date
-- again and deactivates the decision about the old date.
create or replace function public.reset_edited_acquisition_date()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
    if coalesce(current_setting('deadtrees.recording_date_decision', true), '') = 'on' then
        return new;
    end if;
    if (new.aquisition_year, new.aquisition_month, new.aquisition_day)
        is distinct from (old.aquisition_year, old.aquisition_month, old.aquisition_day) then
        new.aquisition_date_source := 'reported';
        new.aquisition_date_decision_id := null;
        perform public.supersede_acquisition_date_decision(new.id, 'date_edited');
    end if;
    return new;
end;
$$;
revoke all on function public.reset_edited_acquisition_date() from public, anon, authenticated;
drop trigger if exists reset_edited_acquisition_date on public.v2_datasets;
create trigger reset_edited_acquisition_date
before update of aquisition_year, aquisition_month, aquisition_day on public.v2_datasets
for each row execute function public.reset_edited_acquisition_date();

-- A new estimate of the date the active decision left on the dataset
-- deactivates it when it disagrees: the decision found the date fine (valid,
-- or a suggestion accepted) but the estimate flags a huge mismatch; or it
-- found the date wrong and kept it, but the estimate sees no problem; or the
-- month is missing and a suggestion now exists that nobody decided on.
create or replace function public.supersede_contradicted_date_decision()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
    v_active record;
    v_fine boolean;
begin
    select * into v_active from public.acquisition_date_decisions a
    where a.dataset_id = new.dataset_id and a.superseded_at is null;
    if v_active.id is null then
        return null;
    end if;
    if (new.recorded_year, new.recorded_month, new.recorded_day)
        is distinct from (v_active.resulting_year, v_active.resulting_month, v_active.resulting_day) then
        return null;
    end if;
    -- coalesce: without a suggestion the comparison is null, and false or null is null
    v_fine := v_active.date_valid or coalesce(v_active.suggestion_decision = 'accepted', false);
    if (v_fine and new.is_mismatch)
        or (not v_fine and not new.is_mismatch and new.suggestion_reason is null)
        or (new.suggestion_reason = 'missing_month' and v_active.suggestion_decision is null) then
        perform public.supersede_acquisition_date_decision(new.dataset_id, 'estimate_contradicts');
    end if;
    return null;
end;
$$;
revoke all on function public.supersede_contradicted_date_decision() from public, anon, authenticated;
drop trigger if exists supersede_contradicted_date_decision on public.v2_acquisition_date_estimates;
create trigger supersede_contradicted_date_decision
after insert or update on public.v2_acquisition_date_estimates
for each row execute function public.supersede_contradicted_date_decision();

-- Automatic decisions (processor setting DOY_AUTO_DECIDE): the prefill becomes
-- the decision unless a person already decided.
create or replace function public.record_automatic_acquisition_date_decision(p_dataset_id bigint)
returns bigint language plpgsql security definer set search_path = '' as $$
declare
    v_est record;
begin
    if (auth.jwt() ->> 'email') is distinct from 'processor@deadtrees.earth' then
        raise exception 'Only the processor records automatic date decisions' using errcode = '42501';
    end if;
    select * into v_est from public.v2_acquisition_date_estimates e where e.dataset_id = p_dataset_id;
    if v_est.dataset_id is null then
        return null;
    end if;
    return public.record_acquisition_date_decision(
        p_dataset_id, not v_est.is_mismatch,
        case when v_est.suggested_date is not null then coalesce(v_est.recommend_accept, false) end,
        'automatic', null);
end;
$$;
revoke all on function public.record_automatic_acquisition_date_decision(bigint) from public, anon;
grant execute on function public.record_automatic_acquisition_date_decision(bigint) to authenticated, service_role;

-- Operator step after a model upgrade or policy change: deactivate every
-- active decision made before a date, so those datasets are re-checked.
create or replace function public.supersede_acquisition_date_decisions_before(p_decided_before timestamptz)
returns integer language plpgsql security definer set search_path = '' as $$
declare
    v_dataset bigint;
    v_count integer := 0;
begin
    for v_dataset in
        select dataset_id from public.acquisition_date_decisions
        where superseded_at is null and decided_at < p_decided_before
    loop
        perform public.supersede_acquisition_date_decision(v_dataset, 'cutoff');
        v_count := v_count + 1;
    end loop;
    return v_count;
end;
$$;
revoke all on function public.supersede_acquisition_date_decisions_before(timestamptz) from public, anon, authenticated;
grant execute on function public.supersede_acquisition_date_decisions_before(timestamptz) to service_role;

-- Datasets whose date step needs a (new) decision, with why.
create or replace view public.acquisition_date_review_queue
with (security_invoker = true) as
select
    e.dataset_id,
    e.model_version,
    e.is_mismatch,
    e.suggested_date,
    e.suggestion_reason,
    e.recommend_accept,
    last.superseded_at as deactivated_at,
    last.superseded_reason as deactivated_reason
from public.v2_acquisition_date_estimates e
left join lateral (
    select a.superseded_at, a.superseded_reason
    from public.acquisition_date_decisions a
    where a.dataset_id = e.dataset_id
    order by a.decided_at desc
    limit 1
) last on true
where not exists (
    select 1 from public.acquisition_date_decisions a
    where a.dataset_id = e.dataset_id and a.superseded_at is null
);
grant select on public.acquisition_date_review_queue to authenticated, service_role;

-- The audit page loads a saved audit through this RPC; it must return the
-- accept field, or a saved "keep reported date" would look empty and be
-- prefilled over. The return type changes, so recreate.
drop function if exists public.get_dataset_audit_with_emails(integer);
create function public.get_dataset_audit_with_emails(p_dataset_id integer)
 returns table(dataset_id integer, audit_date timestamp with time zone, is_georeferenced boolean, has_valid_acquisition_date boolean, acquisition_date_notes text, has_valid_phenology boolean, phenology_notes text, deadwood_quality text, deadwood_notes text, forest_cover_quality text, forest_cover_notes text, aoi_done boolean, has_cog_issue boolean, cog_issue_notes text, has_thumbnail_issue boolean, thumbnail_issue_notes text, audited_by uuid, notes text, has_major_issue boolean, final_assessment text, reviewed_at timestamp with time zone, reviewed_by uuid, audited_by_email text, uploaded_by_email text, reviewed_by_email text, accept_suggested_acquisition_date boolean)
 language plpgsql
 security definer
 set search_path to 'public', 'auth'
as $function$
begin
	if not can_audit() then
		raise exception 'forbidden' using errcode = '42501';
	end if;

	return query
	select
		da.dataset_id::integer,
		da.audit_date,
		da.is_georeferenced,
		da.has_valid_acquisition_date,
		da.acquisition_date_notes,
		da.has_valid_phenology,
		da.phenology_notes,
		da.deadwood_quality::text,
		da.deadwood_notes,
		da.forest_cover_quality::text,
		da.forest_cover_notes,
		da.aoi_done,
		da.has_cog_issue,
		da.cog_issue_notes,
		da.has_thumbnail_issue,
		da.thumbnail_issue_notes,
		da.audited_by,
		da.notes,
		da.has_major_issue,
		da.final_assessment,
		da.reviewed_at,
		da.reviewed_by,
		au.email::text as audited_by_email,
		uu.email::text as uploaded_by_email,
		ru.email::text as reviewed_by_email,
		da.accept_suggested_acquisition_date
	from dataset_audit da
	left join auth.users au on da.audited_by = au.id
	left join v2_datasets d on da.dataset_id = d.id
	left join auth.users uu on d.user_id = uu.id
	left join auth.users ru on da.reviewed_by = ru.id
	where da.dataset_id = p_dataset_id::bigint;
end;
$function$;
revoke all on function public.get_dataset_audit_with_emails(integer) from public, anon;
grant execute on function public.get_dataset_audit_with_emails(integer) to authenticated, service_role;
