-- Log open-vocabulary search queries for analytics.
--
-- Both the global dataset search (/dataset archive) and the per-orthophoto tile
-- search first embed a free-text query and then rank through Supabase RPCs. This
-- table records successful privileged searches: the text, the user, and the
-- dataset (only for dataset-scoped tile search; NULL for global search).
-- Anonymous search, when enabled later, must not write raw query text here.

create table "public"."v2_search_queries" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    -- Match the API's validated maximum so no row can become a large blob.
    "query" text not null check (char_length(query) <= 300),
    -- The insert policy requires this to match the authenticated auditor.
    "user_id" uuid default auth.uid(),
    -- Set only for dataset-scoped tile searches; NULL for the global search.
    "dataset_id" bigint
);

alter table "public"."v2_search_queries" enable row level security;

CREATE UNIQUE INDEX v2_search_queries_pkey ON public.v2_search_queries USING btree (id);
alter table "public"."v2_search_queries" add constraint "v2_search_queries_pkey" PRIMARY KEY using index "v2_search_queries_pkey";

-- Keep the log row if the user or dataset is later removed (analytics history),
-- just null the reference.
alter table "public"."v2_search_queries"
  add constraint "v2_search_queries_user_id_fkey"
  foreign key (user_id) references auth.users(id) on delete set null not valid;
alter table "public"."v2_search_queries" validate constraint "v2_search_queries_user_id_fkey";

alter table "public"."v2_search_queries"
  add constraint "v2_search_queries_dataset_id_fkey"
  foreign key (dataset_id) references public.v2_datasets(id) on delete set null not valid;
alter table "public"."v2_search_queries" validate constraint "v2_search_queries_dataset_id_fkey";

-- Analytics access patterns: recent-first, and per-dataset.
CREATE INDEX v2_search_queries_created_at_idx ON public.v2_search_queries USING btree (created_at desc);
CREATE INDEX v2_search_queries_dataset_id_idx ON public.v2_search_queries USING btree (dataset_id);

-- The browser writes only after its ranking RPC succeeds. RLS restricts inserts
-- to the authenticated auditor's own row and reads to auditors.
revoke all on table "public"."v2_search_queries" from "anon";
revoke update, delete, truncate, references, trigger
  on table "public"."v2_search_queries" from "authenticated";
grant select, insert on table "public"."v2_search_queries" to "authenticated";
grant all on table "public"."v2_search_queries" to "service_role";

revoke all on sequence "public"."v2_search_queries_id_seq" from "anon";
grant usage, select on sequence "public"."v2_search_queries_id_seq" to "authenticated", "service_role";

create policy "Auditors can log their successful search query"
on "public"."v2_search_queries"
as permissive
for insert
to authenticated
with check (
  user_id = auth.uid()
  and public.can_audit()
);

-- Read: analytics only — restricted to auditors.
create policy "Auditors can read the search query log"
on "public"."v2_search_queries"
as permissive
for select
to authenticated
using (exists (
  select 1 from public.privileged_users
  where privileged_users.user_id = auth.uid()
    and privileged_users.can_audit = true
));
