-- Track AOI provenance so machine-generated AOIs can be preserved separately
-- from auditor/manual corrections.

alter table public.v2_aois
  add column if not exists source text not null default 'manual';

alter table public.v2_aois
  add column if not exists corrected_from_aoi_id bigint references public.v2_aois(id) on delete set null;

alter table public.v2_aois
  drop constraint if exists v2_aois_source_check;

alter table public.v2_aois
  add constraint v2_aois_source_check
  check (source in ('ml_prediction', 'manual', 'manual_correction'));

update public.v2_aois a
set source = 'ml_prediction'
where a.notes = 'Auto-generated by aoi_segmentation_v1'
  or exists (
    select 1
    from auth.users u
    where u.id = a.user_id
      and u.email = 'processor@deadtrees.earth'
  );

-- Keep the migration compatible with processors deployed before the source
-- field was added. PostgreSQL applies the column default before this trigger.
create or replace function public.normalize_legacy_processor_aoi_source()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if new.source = 'manual'
    and new.user_id = auth.uid()
    and (auth.jwt() ->> 'email') = 'processor@deadtrees.earth'
  then
    new.source := 'ml_prediction';
  end if;

  return new;
end;
$$;

drop trigger if exists normalize_legacy_processor_aoi_source on public.v2_aois;
create trigger normalize_legacy_processor_aoi_source
  before insert on public.v2_aois
  for each row
  execute function public.normalize_legacy_processor_aoi_source();

create or replace function public.enforce_aoi_identity_immutable()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if new.dataset_id is distinct from old.dataset_id
    or new.user_id is distinct from old.user_id
    or new.source is distinct from old.source
    or new.corrected_from_aoi_id is distinct from old.corrected_from_aoi_id
  then
    raise exception 'AOI ownership and provenance fields are immutable'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_aoi_identity_immutable on public.v2_aois;
create trigger enforce_aoi_identity_immutable
  before update on public.v2_aois
  for each row
  execute function public.enforce_aoi_identity_immutable();

create index if not exists idx_aois_dataset_source_created_at
  on public.v2_aois(dataset_id, source, created_at desc);

create index if not exists idx_aois_corrected_from_aoi_id
  on public.v2_aois(corrected_from_aoi_id);

drop policy if exists "Allow authenticated users to create AOIs" on public.v2_aois;
create policy "Allow authenticated users to create AOIs"
  on public.v2_aois
  for insert
  to authenticated
  with check (
    auth.uid() = user_id
    and (
      (
        source = 'ml_prediction'
        and ((auth.jwt() ->> 'email'::text) = 'processor@deadtrees.earth'::text)
      )
      or (
        source in ('manual', 'manual_correction')
        and (
          exists (
            select 1
            from public.v2_datasets d
            where d.id = dataset_id
              and d.user_id = auth.uid()
          )
          or can_audit()
        )
      )
    )
  );

drop policy if exists "Allow users to update their own AOIs" on public.v2_aois;
create policy "Allow users to update manual AOIs"
  on public.v2_aois
  for update
  to authenticated
  using (
    source in ('manual', 'manual_correction')
    and (
      (
        auth.uid() = user_id
        and exists (
          select 1
          from public.v2_datasets d
          where d.id = dataset_id
            and d.user_id = auth.uid()
        )
      )
      or can_audit()
    )
  )
  with check (
    source in ('manual', 'manual_correction')
    and (
      (
        auth.uid() = user_id
        and exists (
          select 1
          from public.v2_datasets d
          where d.id = dataset_id
            and d.user_id = auth.uid()
        )
      )
      or can_audit()
    )
  );

drop policy if exists "Allow users to delete their own AOIs" on public.v2_aois;
create policy "Allow processor and owners to delete AOIs"
  on public.v2_aois
  for delete
  to authenticated
  using (
    (
      source = 'ml_prediction'
      and auth.uid() = user_id
      and ((auth.jwt() ->> 'email'::text) = 'processor@deadtrees.earth'::text)
    )
    or (
      source in ('manual', 'manual_correction')
      and auth.uid() = user_id
      and (
        exists (
          select 1
          from public.v2_datasets d
          where d.id = dataset_id
            and d.user_id = auth.uid()
        )
        or can_audit()
      )
    )
  );
