from pathlib import Path

from shared.logger import logger
from shared.logging import LogContext, LogCategory
from shared.models import AOI, AOI_V1_MODEL_CHECKPOINT_NAME
from shared.db import login, use_client
from shared.settings import settings

from ..exceptions import ProcessingError
from ..utils.segmentation import polygons_to_multipolygon_geojson
from ..utils.geometry_validation import validate_and_fix_polygons
from .inference import AOIInference

PROJECT_ROOT = Path(__file__).parent.parent.parent.parent
ASSETS_DIR = PROJECT_ROOT / 'assets'

MODEL_PATH = str(ASSETS_DIR / 'models' / AOI_V1_MODEL_CHECKPOINT_NAME)

# Marker stored on auto-generated AOIs so reruns can replace their own previous
# output without touching auditor-drawn AOIs.
AUTO_AOI_NOTES = 'Auto-generated by aoi_segmentation_v1'


def predict_aoi(dataset_id: int, file_path: Path, user_id: str, token: str):
	"""Generate and store an Area-of-Interest polygon for a dataset.

	Runs the SegFormer-B1 AOI model on the orthomosaic, cleans the predicted
	boundary into one polygon, and writes it to ``v2_aois`` so auditors start
	from a prediction. Idempotent: a previous auto-generated AOI for the same
	dataset is removed before the new one is written.
	"""
	try:
		log = lambda msg, **extra: logger.info(
			msg,
			LogContext(category=LogCategory.AOI, dataset_id=dataset_id, user_id=user_id, token=token, extra=extra),
		)

		log('Initializing AOI inference model')
		model = AOIInference(model_path=MODEL_PATH)

		log('Running AOI inference', file_path=str(file_path))
		polygons = model.inference(str(file_path))

		# Inference can run longer than the JWT lifetime (~1h), which would make
		# the subsequent AOI writes fail with PGRST303 'JWT expired'. Refresh the
		# token now that the long-running work is done and DB writes are imminent.
		token = login(settings.PROCESSOR_USERNAME, settings.PROCESSOR_PASSWORD)

		_save_aoi(
			polygons=polygons,
			dataset_id=dataset_id,
			user_id=user_id,
			token=token,
		)

	except Exception as e:
		logger.error(
			f'Error in predict_aoi: {str(e)}',
			LogContext(category=LogCategory.AOI, dataset_id=dataset_id, user_id=user_id, token=token),
		)
		raise ProcessingError(str(e), task_type='aoi_segmentation', dataset_id=dataset_id)


def _save_aoi(polygons, dataset_id, user_id, token):
	log_ctx = LogContext(category=LogCategory.AOI, dataset_id=dataset_id, user_id=user_id, token=token)

	if polygons is None or len(polygons) == 0:
		logger.warning('No AOI polygon detected; skipping AOI write', log_ctx)
		return

	# Polygons are already in EPSG:4326 from inference; validate/repair geometry.
	polygons, _ = validate_and_fix_polygons(polygons, min_area=0.0, dataset_id=dataset_id, label_type='aoi')
	if len(polygons) == 0:
		logger.warning('No valid AOI polygon after geometry validation; skipping AOI write', log_ctx)
		return

	geojson = polygons_to_multipolygon_geojson(polygons)

	aoi = AOI(
		dataset_id=dataset_id,
		user_id=user_id,
		geometry=geojson,
		is_whole_image=False,
		notes=AUTO_AOI_NOTES,
	)

	with use_client(token) as client:
		# Replace only our own previous auto-generated AOI; never delete
		# auditor-drawn AOIs (which carry different/no notes).
		client.table(settings.aois_table).delete().eq('dataset_id', dataset_id).eq('notes', AUTO_AOI_NOTES).execute()
		response = (
			client.table(settings.aois_table)
			.insert(aoi.model_dump(exclude={'id', 'created_at', 'updated_at'}))
			.execute()
		)

	aoi_id = response.data[0]['id']
	logger.info(f'Created auto-generated AOI {aoi_id}', log_ctx)
